config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: develop
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cerulean-jaguar.sh
        container: qc.acc_jumpy-maroon-clam
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-seashell-dachsbracke.sh
        container: qc.doc_goopy-tangerine-avocet
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-plum-crane.sh
        container: qc.doc_silly-tangerine-argentino
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-bronze-barb.sh
        container: qc.doc_flaky-cerise-cockroach
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-coral-yak.sh
        container: qc.lic_shaggy-emerald-zebu
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-apricot-lemming.sh
        container: qc.sec_flabby-rust-maltese
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-cardinal-slug.sh
        container: qc.sty_greasy-magenta-dhole
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-bronze-elephant.sh
        container: qc.uni_pasty-jade-quetzal
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-heliotrope-dragon.sh
        container: qc.ver_geeky-vermilion-serval
timeout: 5400
