config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: master
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-mauve-seal.sh
        container: qc.acc_foggy-orange-impala
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-orchid-pinscher.sh
        container: qc.doc_flaky-indigo-labradoodle
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-myrtle-blue.sh
        container: qc.doc_flabby-champagne-peccary
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-fuchsia-frise.sh
        container: qc.doc_dorky-khaki-bat
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-chocolate-hamster.sh
        container: qc.lic_geeky-taupe-fly
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-tomato-ibis.sh
        container: qc.met_wimpy-ochre-camel
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-heliotrope-zorse.sh
        container: qc.sec_shabby-blue-mandrill
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-lemon-millipede.sh
        container: qc.sty_leaky-buff-mongrel
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cinnabar-bulldog.sh
        container: qc.uni_hasty-apricot-beagle
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-ochre-ferret.sh
        container: qc.ver_wimpy-auburn-koala
timeout: 5400
