config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: master
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-sepia-alligator.sh
        container: qc.acc_cloudy-orange-angora
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-orange-corgi.sh
        container: qc.doc_shabby-firebrick-octopus
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-yellow-gecko.sh
        container: qc.doc_squirrely-denim-indri
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cardinal-iguana.sh
        container: qc.doc_cozy-olive-dragonfly
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chartreuse-birman.sh
        container: qc.lic_grumpy-seashell-sheep
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.messy-burgundy-vulture.sh
        container: qc.met_snappy-periwinkle-jackal
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-magnolia-barnacle.sh
        container: qc.sec_lousy-emerald-chimpanzee
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-aquamarine-bison.sh
        container: qc.sty_clammy-asparagus-horse
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-viridian-yak.sh
        container: qc.uni_pokey-heliotrope-snake
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-lilac-beagle.sh
        container: qc.ver_foggy-amber-barnacle
timeout: 5400
