config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: master
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-chestnut-walrus.sh
        container: qc.acc_wheezy-ruby-chow
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-rust-gerbil.sh
        container: qc.doc_tacky-red-dodo
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-sepia-sheepdog.sh
        container: qc.doc_sleepy-flax-newt
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-sangria-stoat.sh
        container: qc.doc_craggy-russet-coral
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-zucchini-cougar.sh
        container: qc.lic_randy-goldenrod-whippet
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-malachite-monster.sh
        container: qc.met_boozy-bistre-toucan
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-jade-moth.sh
        container: qc.sec_nippy-auburn-eel
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-aquamarine-wrasse.sh
        container: qc.sty_pretty-bistre-lemming
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-orange-indri.sh
        container: qc.uni_skanky-ruby-hare
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-maroon-crocodile.sh
        container: qc.ver_hazy-mauve-audemer
timeout: 5400
