config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: master
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-scarlet-echidna.sh
        container: qc.acc_fuzzy-amber-whale
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-thistle-blue.sh
        container: qc.doc_grumpy-buff-flounder
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-jade-collie.sh
        container: qc.doc_muzzy-olivine-seal
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-vermilion-balinese.sh
        container: qc.doc_homey-persimmon-harrier
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-grey-zebra.sh
        container: qc.lic_nippy-ivory-goat
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-auburn-chinook.sh
        container: qc.met_shabby-platinum-setter
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-persimmon-argentino.sh
        container: qc.sec_homey-champagne-neanderthal
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-malachite-cockroach.sh
        container: qc.sty_crappy-auburn-impala
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-fuchsia-sparrow.sh
        container: qc.uni_nippy-coral-chicken
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-lilac-harrier.sh
        container: qc.ver_slimy-plum-owl
timeout: 5400
