config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: master
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-sepia-hummingbird.sh
        container: qc.acc_chewy-fuchsia-scorpion
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-harlequin-peccary.sh
        container: qc.doc_sunny-champagne-squirrel
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-silver-kakapo.sh
        container: qc.doc_blurry-ivory-eagle
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-platinum-mau.sh
        container: qc.doc_nippy-ultramarine-harrier
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homely-pink-zebu.sh
        container: qc.lic_shaggy-cinnamon-gopher
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-yellow-hare.sh
        container: qc.met_flabby-brass-uakari
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-copper-crab.sh
        container: qc.sec_wheezy-ultramarine-dalmatian
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-plum-avocet.sh
        container: qc.sty_beady-pink-walrus
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-turquoise-bullfrog.sh
        container: qc.uni_trippy-jade-cattle
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-turquoise-cow.sh
        container: qc.ver_cranky-carmine-tiger
timeout: 5400
