config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: master
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-pumpkin-shrew.sh
        container: qc.acc_breezy-beige-pig
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-bronze-jackal.sh
        container: qc.doc_slimy-wisteria-wolf
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-white-centipede.sh
        container: qc.doc_squirrely-white-cuscus
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-maroon-uakari.sh
        container: qc.doc_greasy-alizarin-armadillo
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-brass-affenpinscher.sh
        container: qc.lic_fuzzy-dandelion-snail
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-celadon-slug.sh
        container: qc.sec_sunny-denim-walrus
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-mustard-koala.sh
        container: qc.sty_queasy-bronze-dachshund
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-razzmatazz-antelope.sh
        container: qc.uni_flabby-saffron-toucan
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-ultramarine-cassowary.sh
        container: qc.ver_slaphappy-smalt-manatee
timeout: 5400
