config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IraitzM/data-complexity:
      branch: master
      repo: https://github.com/IraitzM/data-complexity
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-persimmon-markhor.sh
        container: qc.acc_cheeky-black-centipede
  QC.Doc:
    repos:
      github.com/IraitzM/data-complexity find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-olivine-hyrax.sh
        container: qc.doc_fuzzy-azure-bloodhound
      github.com/IraitzM/data-complexity git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-aqua-axolotl.sh
        container: qc.doc_squirrely-pink-penguin
      github.com/IraitzM/data-complexity markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-ultramarine-chin.sh
        container: qc.doc_sunny-cerulean-caiman
  QC.Lic:
    repos:
      github.com/IraitzM/data-complexity licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-indigo-grasshopper.sh
        container: qc.lic_fuzzy-asparagus-chin
  QC.Met:
    repos:
      github.com/IraitzM/data-complexity cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-chocolate-lemur.sh
        container: qc.met_blurry-olivine-ferret
  QC.Sec:
    repos:
      github.com/IraitzM/data-complexity bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-burgundy-tapir.sh
        container: qc.sec_nippy-asparagus-dunker
  QC.Sty:
    repos:
      github.com/IraitzM/data-complexity flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-maroon-zonkey.sh
        container: qc.sty_scaly-ochre-peccary
  QC.Uni:
    repos:
      github.com/IraitzM/data-complexity pytest:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-fuchsia-rhinoceros.sh
        container: qc.uni_sleepy-flax-emu
  QC.Ver:
    repos:
      github.com/IraitzM/data-complexity get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-chocolate-dunker.sh
        container: qc.ver_lovely-plum-cuttlefish
timeout: 5400
